### ISSUE TITLE
keszlet_gymlap_insert eljárás optimalizálás mobilhoz

### ISSUE THREAD

**Issue by vectorvinczejozsef** [vectorvinczejozsef/vmd#32]

**Comment by vectorhammergergo** [comment]
Kell egy új szemelykod bemenő paraméter hozzá.
A system_user helyett ugyintezo = @szemelykod, es top 1 legyen, mert ugyintezo nem unique stationban.

**Comment by vectorvinczejozsef** [comment]
kész
