### ISSUE TITLE
Gyorsmunkalap kérdések

### ISSUE THREAD

**Issue by vectorvinczejozsef** [vectorvinczejozsef/vmd#33]
Erőforrást kiválasztva, csak az erőforráshoz tartozó projektet lehet kiválasztani? Mert a vectoryban egy erőforráshoz egy projekt tartozik. 
Vectory:
![image](https://user-images.githubusercontent.com/42992822/45416998-72ed7080-b681-11e8-9565-a0657d914152.png)

Szűrés?:

![image](https://user-images.githubusercontent.com/42992822/45417253-0626a600-b682-11e8-9ee8-8568c7858852.png)

**Comment by vectorhammergergo** [comment]
igen, jöhet az egységár át alapértelmezetten
