### ISSUE TITLE
Vectory-hoz hasonló működésű  keresőmező

### ISSUE THREAD

**Issue by vectorvinczejozsef** [vectorvinczejozsef/vmd#7]
Zozó észrevétele:

> Nekem tetszik. Annyi gondolatom van hozzá, hogy úgy kellene, mint a Vectory-ban is.
> Ha csak simán azt írom, hogy tt, akkor az csak az elejében keressen.
> Ha azt, hogy %tt, vagy *tt akkor keressen mindenhol.

**Comment by vectorvinczejozsef** [comment]
Viktor Észrevétele:

> Alapvetően nekem is tetszik. Szépen alakul a felület.
> Az én véleményem az, hogy egy mobil applikációban felhasználói szemmel nem szeretném, hogy ha beírok valamit, akkor rá kelljen még nyomnom utána a keresés gombra.
> Én úgy oldanám meg, hogy a szöveg beíráskor ne minden gombnyomásra keressen. 
> Hanem a gomb lenyomás után ha egy megadott ideig nem írnak be új karaktert, akkor indítaná a keresést és listázná a találatokat.
> 
> Ezenkívül a *-al és %-al való keresés sem túl felhasználóbarát szerintem.
> Személy szerint, sem applikációban sem weblapon nem alkalmaznám.
>

**Comment by vectorvinczejozsef** [comment]
@vectorpolloviktor , @vectorhammergergo

**Comment by vectorvinczejozsef** [comment]
https://github.com/Pixabay/jQuery-autoComplete

**Comment by vectorpolloviktor** [comment]
Ötletnek:

https://jqueryui.com/autocomplete/#remote
http://demos.jquerymobile.com/1.3.1/widgets/autocomplete/

**Comment by vectorpolloviktor** [comment]
Én az alsót szoktam használni. Be lehet állítani azt is, hogy hány karaktertől keressen.
Meg egy csomó hasznos funkciója van.
